<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Privacy_Actual</name>
   <tag></tag>
   <elementGuidId>ec2c204f-2836-4708-964e-1407a8182693</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='This is the terms and conditions document. We are not yet ready with it. Stay tuned!&quot;']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>2ad4943e-f5a3-4dc1-9e2b-ee66e3094cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is the terms and conditions document. We are not yet ready with it. Stay tuned!&quot;</value>
      <webElementGuid>17074819-d868-4950-9b3a-13fe454f7b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]</value>
      <webElementGuid>1e065b86-5888-4aa3-bec3-79ef4af99847</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This is the terms and conditions document. We are not yet ready with it. Stay tuned!&quot;']/parent::*</value>
      <webElementGuid>1d7bcc94-f7d9-4738-9fd9-14f24a40f9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>d46b4996-e87b-4058-ba85-4842a274dae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = 'This is the terms and conditions document. We are not yet ready with it. Stay tuned!&quot;Capture object: Alt ` ● Load DOM Map: Ctrl Alt ` ' or . = 'This is the terms and conditions document. We are not yet ready with it. Stay tuned!&quot;Capture object: Alt ` ● Load DOM Map: Ctrl Alt ` ')]</value>
      <webElementGuid>3cc11eb2-6ac9-4980-9092-1332718a427d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
